Add `error_checking.R`
traitecoevo/traits.build-template pull request #3
Opened 2023-10-19 09:42 UTC by yangsophieee

Addresses [this issue](https://github.com/traitecoevo/traits.build/issues/83) from traits.build:
- Includes custom function for checking duplicates that prevent pivoting wider (helps users identify which rows are the problem when the `dataset_test` `pivot_wider` test fails)
- @ehwenk and I were discussing where would be the appropriate home for this function, but let us know if you have better ideas :)

2023-10-19 19:48 UTC, dfalster requested changes
Hi! Good idea. But I suggest some changes.
1. You should reduce function to one that accepts a traits table and does the check for duplicates. Here's you've included the building of the dataset(s), but that should happen outside the function. 

2. This belongs in traits.build, not this repo

2023-10-19 19:48 UTC, dfalster commented on R/error_checking.R
> +  traits %>%
Turn this part into a function and add to traits.build

2023-10-19 22:31 UTC, yangsophieee commented
@dfalster Thanks for the suggestions! Where exactly should I put the function on traits.build?

2023-10-19 22:33 UTC, dfalster commented
What about in the file `R/setup`? It should be exported and part of the general infrastructure.

2023-10-19 22:35 UTC, yangsophieee commented
Yep I will export it. I thought R/setup is more for building and populating the metadata template files + setting up the build process? This function is for after the database/dataset has been built. But I don't really mind!

2023-10-19 22:36 UTC, dfalster commented
true, maybe put it at the booth of `R/process`

2023-10-19 22:40 UTC, yangsophieee commented
Ok great! What do you mean by booth sorry?

2023-10-20 03:16 UTC, yangsophieee commented
Moved back to `traits.build`, with [this PR](https://github.com/traitecoevo/traits.build/pull/106).

2023-10-20 03:16 UTC, closed without merging